#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaneOtomasyon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pharmacyDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertfatura(fatura instance);
    partial void Updatefatura(fatura instance);
    partial void Deletefatura(fatura instance);
    partial void Insertilacturleri(ilacturleri instance);
    partial void Updateilacturleri(ilacturleri instance);
    partial void Deleteilacturleri(ilacturleri instance);
    partial void Insertmusteri(musteri instance);
    partial void Updatemusteri(musteri instance);
    partial void Deletemusteri(musteri instance);
    partial void Inserttedarikci(tedarikci instance);
    partial void Updatetedarikci(tedarikci instance);
    partial void Deletetedarikci(tedarikci instance);
    partial void Insertilaclar(ilaclar instance);
    partial void Updateilaclar(ilaclar instance);
    partial void Deleteilaclar(ilaclar instance);
    partial void Insertsati(sati instance);
    partial void Updatesati(sati instance);
    partial void Deletesati(sati instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::EczaneOtomasyon.Properties.Settings.Default.pharmacyDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fatura> faturas
		{
			get
			{
				return this.GetTable<fatura>();
			}
		}
		
		public System.Data.Linq.Table<ilacturleri> ilacturleris
		{
			get
			{
				return this.GetTable<ilacturleri>();
			}
		}
		
		public System.Data.Linq.Table<musteri> musteris
		{
			get
			{
				return this.GetTable<musteri>();
			}
		}
		
		public System.Data.Linq.Table<tedarikci> tedarikcis
		{
			get
			{
				return this.GetTable<tedarikci>();
			}
		}
		
		public System.Data.Linq.Table<ilaclar> ilaclars
		{
			get
			{
				return this.GetTable<ilaclar>();
			}
		}
		
		public System.Data.Linq.Table<sati> satis
		{
			get
			{
				return this.GetTable<sati>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fatura")]
	public partial class fatura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fid;
		
		private System.Nullable<int> _fno;
		
		private System.Nullable<int> _satisid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfidChanging(int value);
    partial void OnfidChanged();
    partial void OnfnoChanging(System.Nullable<int> value);
    partial void OnfnoChanged();
    partial void OnsatisidChanging(System.Nullable<int> value);
    partial void OnsatisidChanged();
    #endregion
		
		public fatura()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fid
		{
			get
			{
				return this._fid;
			}
			set
			{
				if ((this._fid != value))
				{
					this.OnfidChanging(value);
					this.SendPropertyChanging();
					this._fid = value;
					this.SendPropertyChanged("fid");
					this.OnfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fno", DbType="Int")]
		public System.Nullable<int> fno
		{
			get
			{
				return this._fno;
			}
			set
			{
				if ((this._fno != value))
				{
					this.OnfnoChanging(value);
					this.SendPropertyChanging();
					this._fno = value;
					this.SendPropertyChanged("fno");
					this.OnfnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satisid", DbType="Int")]
		public System.Nullable<int> satisid
		{
			get
			{
				return this._satisid;
			}
			set
			{
				if ((this._satisid != value))
				{
					this.OnsatisidChanging(value);
					this.SendPropertyChanging();
					this._satisid = value;
					this.SendPropertyChanged("satisid");
					this.OnsatisidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ilacturleri")]
	public partial class ilacturleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _turid;
		
		private string _turadi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnturidChanging(int value);
    partial void OnturidChanged();
    partial void OnturadiChanging(string value);
    partial void OnturadiChanged();
    #endregion
		
		public ilacturleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int turid
		{
			get
			{
				return this._turid;
			}
			set
			{
				if ((this._turid != value))
				{
					this.OnturidChanging(value);
					this.SendPropertyChanging();
					this._turid = value;
					this.SendPropertyChanged("turid");
					this.OnturidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turadi", DbType="NVarChar(30)")]
		public string turadi
		{
			get
			{
				return this._turadi;
			}
			set
			{
				if ((this._turadi != value))
				{
					this.OnturadiChanging(value);
					this.SendPropertyChanging();
					this._turadi = value;
					this.SendPropertyChanged("turadi");
					this.OnturadiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.musteri")]
	public partial class musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mid;
		
		private string _madi;
		
		private string _adres;
		
		private string _telno;
		
		private EntitySet<sati> _satis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmidChanging(int value);
    partial void OnmidChanged();
    partial void OnmadiChanging(string value);
    partial void OnmadiChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OntelnoChanging(string value);
    partial void OntelnoChanged();
    #endregion
		
		public musteri()
		{
			this._satis = new EntitySet<sati>(new Action<sati>(this.attach_satis), new Action<sati>(this.detach_satis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				if ((this._mid != value))
				{
					this.OnmidChanging(value);
					this.SendPropertyChanging();
					this._mid = value;
					this.SendPropertyChanged("mid");
					this.OnmidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madi", DbType="NVarChar(40)")]
		public string madi
		{
			get
			{
				return this._madi;
			}
			set
			{
				if ((this._madi != value))
				{
					this.OnmadiChanging(value);
					this.SendPropertyChanging();
					this._madi = value;
					this.SendPropertyChanged("madi");
					this.OnmadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(40)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telno", DbType="NVarChar(20)")]
		public string telno
		{
			get
			{
				return this._telno;
			}
			set
			{
				if ((this._telno != value))
				{
					this.OntelnoChanging(value);
					this.SendPropertyChanging();
					this._telno = value;
					this.SendPropertyChanged("telno");
					this.OntelnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_sati", Storage="_satis", ThisKey="mid", OtherKey="musteriid")]
		public EntitySet<sati> satis
		{
			get
			{
				return this._satis;
			}
			set
			{
				this._satis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_satis(sati entity)
		{
			this.SendPropertyChanging();
			entity.musteri = this;
		}
		
		private void detach_satis(sati entity)
		{
			this.SendPropertyChanging();
			entity.musteri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tedarikci")]
	public partial class tedarikci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tedarikciid;
		
		private string _tedarikciadi;
		
		private string _tedadres;
		
		private string _tedtelno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntedarikciidChanging(int value);
    partial void OntedarikciidChanged();
    partial void OntedarikciadiChanging(string value);
    partial void OntedarikciadiChanged();
    partial void OntedadresChanging(string value);
    partial void OntedadresChanged();
    partial void OntedtelnoChanging(string value);
    partial void OntedtelnoChanged();
    #endregion
		
		public tedarikci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tedarikciid
		{
			get
			{
				return this._tedarikciid;
			}
			set
			{
				if ((this._tedarikciid != value))
				{
					this.OntedarikciidChanging(value);
					this.SendPropertyChanging();
					this._tedarikciid = value;
					this.SendPropertyChanged("tedarikciid");
					this.OntedarikciidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciadi", DbType="NVarChar(30)")]
		public string tedarikciadi
		{
			get
			{
				return this._tedarikciadi;
			}
			set
			{
				if ((this._tedarikciadi != value))
				{
					this.OntedarikciadiChanging(value);
					this.SendPropertyChanging();
					this._tedarikciadi = value;
					this.SendPropertyChanged("tedarikciadi");
					this.OntedarikciadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedadres", DbType="NVarChar(40)")]
		public string tedadres
		{
			get
			{
				return this._tedadres;
			}
			set
			{
				if ((this._tedadres != value))
				{
					this.OntedadresChanging(value);
					this.SendPropertyChanging();
					this._tedadres = value;
					this.SendPropertyChanged("tedadres");
					this.OntedadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedtelno", DbType="NVarChar(15)")]
		public string tedtelno
		{
			get
			{
				return this._tedtelno;
			}
			set
			{
				if ((this._tedtelno != value))
				{
					this.OntedtelnoChanging(value);
					this.SendPropertyChanging();
					this._tedtelno = value;
					this.SendPropertyChanged("tedtelno");
					this.OntedtelnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ilaclar")]
	public partial class ilaclar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ilacid;
		
		private string _ilacAdi;
		
		private string _ilacTuru;
		
		private System.Nullable<int> _BirimFiyat;
		
		private System.Nullable<int> _Miktar;
		
		private System.Nullable<System.DateTime> _TETT;
		
		private string _FirmaAdi;
		
		private string _SeriNo;
		
		private System.Nullable<bool> _deleted;
		
		private EntitySet<sati> _satis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnilacidChanging(int value);
    partial void OnilacidChanged();
    partial void OnilacAdiChanging(string value);
    partial void OnilacAdiChanged();
    partial void OnilacTuruChanging(string value);
    partial void OnilacTuruChanged();
    partial void OnBirimFiyatChanging(System.Nullable<int> value);
    partial void OnBirimFiyatChanged();
    partial void OnMiktarChanging(System.Nullable<int> value);
    partial void OnMiktarChanged();
    partial void OnTETTChanging(System.Nullable<System.DateTime> value);
    partial void OnTETTChanged();
    partial void OnFirmaAdiChanging(string value);
    partial void OnFirmaAdiChanged();
    partial void OnSeriNoChanging(string value);
    partial void OnSeriNoChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    #endregion
		
		public ilaclar()
		{
			this._satis = new EntitySet<sati>(new Action<sati>(this.attach_satis), new Action<sati>(this.detach_satis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ilacid
		{
			get
			{
				return this._ilacid;
			}
			set
			{
				if ((this._ilacid != value))
				{
					this.OnilacidChanging(value);
					this.SendPropertyChanging();
					this._ilacid = value;
					this.SendPropertyChanged("ilacid");
					this.OnilacidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacAdi", DbType="VarChar(50)")]
		public string ilacAdi
		{
			get
			{
				return this._ilacAdi;
			}
			set
			{
				if ((this._ilacAdi != value))
				{
					this.OnilacAdiChanging(value);
					this.SendPropertyChanging();
					this._ilacAdi = value;
					this.SendPropertyChanged("ilacAdi");
					this.OnilacAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacTuru", DbType="NVarChar(20)")]
		public string ilacTuru
		{
			get
			{
				return this._ilacTuru;
			}
			set
			{
				if ((this._ilacTuru != value))
				{
					this.OnilacTuruChanging(value);
					this.SendPropertyChanging();
					this._ilacTuru = value;
					this.SendPropertyChanged("ilacTuru");
					this.OnilacTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimFiyat", DbType="Int")]
		public System.Nullable<int> BirimFiyat
		{
			get
			{
				return this._BirimFiyat;
			}
			set
			{
				if ((this._BirimFiyat != value))
				{
					this.OnBirimFiyatChanging(value);
					this.SendPropertyChanging();
					this._BirimFiyat = value;
					this.SendPropertyChanged("BirimFiyat");
					this.OnBirimFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Int")]
		public System.Nullable<int> Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this.OnMiktarChanging(value);
					this.SendPropertyChanging();
					this._Miktar = value;
					this.SendPropertyChanged("Miktar");
					this.OnMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TETT", DbType="Date")]
		public System.Nullable<System.DateTime> TETT
		{
			get
			{
				return this._TETT;
			}
			set
			{
				if ((this._TETT != value))
				{
					this.OnTETTChanging(value);
					this.SendPropertyChanging();
					this._TETT = value;
					this.SendPropertyChanged("TETT");
					this.OnTETTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(30)")]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this.OnFirmaAdiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdi = value;
					this.SendPropertyChanged("FirmaAdi");
					this.OnFirmaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeriNo", DbType="NVarChar(20)")]
		public string SeriNo
		{
			get
			{
				return this._SeriNo;
			}
			set
			{
				if ((this._SeriNo != value))
				{
					this.OnSeriNoChanging(value);
					this.SendPropertyChanging();
					this._SeriNo = value;
					this.SendPropertyChanged("SeriNo");
					this.OnSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ilaclar_sati", Storage="_satis", ThisKey="ilacid", OtherKey="ilacid")]
		public EntitySet<sati> satis
		{
			get
			{
				return this._satis;
			}
			set
			{
				this._satis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_satis(sati entity)
		{
			this.SendPropertyChanging();
			entity.ilaclar = this;
		}
		
		private void detach_satis(sati entity)
		{
			this.SendPropertyChanging();
			entity.ilaclar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.satis")]
	public partial class sati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sid;
		
		private System.Nullable<int> _ilacid;
		
		private System.Nullable<int> _musteriid;
		
		private System.Nullable<System.DateTime> _satistarihi;
		
		private System.Nullable<int> _miktari;
		
		private System.Nullable<int> _toplamfiyat;
		
		private EntityRef<musteri> _musteri;
		
		private EntityRef<ilaclar> _ilaclar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsidChanging(int value);
    partial void OnsidChanged();
    partial void OnilacidChanging(System.Nullable<int> value);
    partial void OnilacidChanged();
    partial void OnmusteriidChanging(System.Nullable<int> value);
    partial void OnmusteriidChanged();
    partial void OnsatistarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnsatistarihiChanged();
    partial void OnmiktariChanging(System.Nullable<int> value);
    partial void OnmiktariChanged();
    partial void OntoplamfiyatChanging(System.Nullable<int> value);
    partial void OntoplamfiyatChanged();
    #endregion
		
		public sati()
		{
			this._musteri = default(EntityRef<musteri>);
			this._ilaclar = default(EntityRef<ilaclar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sid
		{
			get
			{
				return this._sid;
			}
			set
			{
				if ((this._sid != value))
				{
					this.OnsidChanging(value);
					this.SendPropertyChanging();
					this._sid = value;
					this.SendPropertyChanged("sid");
					this.OnsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacid", DbType="Int")]
		public System.Nullable<int> ilacid
		{
			get
			{
				return this._ilacid;
			}
			set
			{
				if ((this._ilacid != value))
				{
					if (this._ilaclar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnilacidChanging(value);
					this.SendPropertyChanging();
					this._ilacid = value;
					this.SendPropertyChanged("ilacid");
					this.OnilacidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musteriid", DbType="Int")]
		public System.Nullable<int> musteriid
		{
			get
			{
				return this._musteriid;
			}
			set
			{
				if ((this._musteriid != value))
				{
					if (this._musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmusteriidChanging(value);
					this.SendPropertyChanging();
					this._musteriid = value;
					this.SendPropertyChanged("musteriid");
					this.OnmusteriidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satistarihi", DbType="Date")]
		public System.Nullable<System.DateTime> satistarihi
		{
			get
			{
				return this._satistarihi;
			}
			set
			{
				if ((this._satistarihi != value))
				{
					this.OnsatistarihiChanging(value);
					this.SendPropertyChanging();
					this._satistarihi = value;
					this.SendPropertyChanged("satistarihi");
					this.OnsatistarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miktari", DbType="Int")]
		public System.Nullable<int> miktari
		{
			get
			{
				return this._miktari;
			}
			set
			{
				if ((this._miktari != value))
				{
					this.OnmiktariChanging(value);
					this.SendPropertyChanging();
					this._miktari = value;
					this.SendPropertyChanged("miktari");
					this.OnmiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toplamfiyat", DbType="Int")]
		public System.Nullable<int> toplamfiyat
		{
			get
			{
				return this._toplamfiyat;
			}
			set
			{
				if ((this._toplamfiyat != value))
				{
					this.OntoplamfiyatChanging(value);
					this.SendPropertyChanging();
					this._toplamfiyat = value;
					this.SendPropertyChanged("toplamfiyat");
					this.OntoplamfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="musteri_sati", Storage="_musteri", ThisKey="musteriid", OtherKey="mid", IsForeignKey=true)]
		public musteri musteri
		{
			get
			{
				return this._musteri.Entity;
			}
			set
			{
				musteri previousValue = this._musteri.Entity;
				if (((previousValue != value) 
							|| (this._musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._musteri.Entity = null;
						previousValue.satis.Remove(this);
					}
					this._musteri.Entity = value;
					if ((value != null))
					{
						value.satis.Add(this);
						this._musteriid = value.mid;
					}
					else
					{
						this._musteriid = default(Nullable<int>);
					}
					this.SendPropertyChanged("musteri");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ilaclar_sati", Storage="_ilaclar", ThisKey="ilacid", OtherKey="ilacid", IsForeignKey=true)]
		public ilaclar ilaclar
		{
			get
			{
				return this._ilaclar.Entity;
			}
			set
			{
				ilaclar previousValue = this._ilaclar.Entity;
				if (((previousValue != value) 
							|| (this._ilaclar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ilaclar.Entity = null;
						previousValue.satis.Remove(this);
					}
					this._ilaclar.Entity = value;
					if ((value != null))
					{
						value.satis.Add(this);
						this._ilacid = value.ilacid;
					}
					else
					{
						this._ilacid = default(Nullable<int>);
					}
					this.SendPropertyChanged("ilaclar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
